version: '2'
services:
  jenkins_agent-ansibleaws:
    container_name: jenkins_agent-ansibleaws
    image: jenkins_agent-ansibleaws:${ANSIBLE_VERSION}
    mem_limit: 1000m
    build:
      context: jenkins_agent-ansibleaws
      dockerfile: Dockerfile
      args:
        - AWS_VAULT_VERSION=${AWS_VAULT_VERSION}
        - ANSIBLE_VERSION=${ANSIBLE_VERSION}
