version: '2'
services:
  terratools:
    container_name: terratools
    image: rendanic/terratools:${TERRAFORM_VERSION}
    hostname: terratools-${TERRAFORM_VERSION}
    mem_limit: 1000m
    volumes:
      - "awsconfig:/home/terraform"
    environment:
      - "PS1=$$(whoami)@$$(hostname):$$(pwd) $$ "
      - "TsERRAGRUNT_DOWNLOAD=/home/terraform/.terragrunt_cache"
volumes:
  awsconfig:
