version: '2'
services:
  terratools:
    container_name: terratools
    image: terratools:0.12.7
    mem_limit: 1000m
    build:
      context: terratools
      dockerfile: Dockerfile
      args:
      - TERRAFORM_VERSION=0.12.7
      - TERRAGRUNT_VERSION=0.19.21
      - AWS_VAULT_VERSION=4.6.3
    volumes:
      - "awsconfig:/home/terraform"

volumes:
  awsconfig: