version: '2'
services:
  terratools:
    container_name: terratools
    image: rendanic/terratools:${TERRAFORM_VERSION}
    mem_limit: 1000m
    volumes:
      - "awsconfig:/home/terraform"

volumes:
  awsconfig: