name: Dockerhub Image CI for ansibleaws

on:

  push:
    branches:
      - master
    paths:
    - 'ansibleaws/ansibleawss/Dockerfile'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Images for ansibleaws
      run: ansibleaws/build_all.sh
      shell: bash
      env:
        dockerpass: ${{ secrets.dockerpass }}
        dockeruser: ${{ secrets.dockeruser }}
    - name: Show Images
      run: docker images | grep ^rendanic | sort