name: Dockerhub Image CI

on: [push]
  branches:
    - master

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Images for terratools
      run: terraform/build_all.sh
      shell: bash