name: CI Jenkins-Agent ansibleaws

on:

  push:
    branches:
      - master
    paths:
      - jenkins-agent/ansibleaws/github_build.sh
      - jenkins-agent/ansibleaws/ansibleaws/Dockerfile

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Images for Jenkins-Agent ansibleaws
      run: jenkins-agent/ansibleaws/github_build.sh
      shell: bash
      env:
        dockerpass: ${{ secrets.dockerpass }}
        dockeruser: ${{ secrets.dockeruser }}
    - name: Show Images
      run: docker images | grep ^rendanic | sort
