name: Dockerhub Image CI for terratools

on:

  push:
    branches:
      - master
    paths:
    - 'terraform/**'

jobs:

  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v1
    - name: Build Images for terratools
      run: terraform/build_all.sh
      shell: bash
      env:
        dockerpass: ${{ secrets.dockerpass }}
        dockeruser: ${{ secrets.dockeruser }}
    - name: Show Images
      run: docker images | grep ^rendanic | sort